export const MIN_LENGTH_ERR = 'MIN_LENGTH_ERR';
export const MAX_LENGTH_ERR = 'MAX_LENGTH_ERR';
export const MANDATORY_ERR = 'MANDATORY_ERR';
export const NUMBER_ERR = 'NUMBER_ERR';
export const ALPHA_ERR = 'ALPHA_ERR';
export const ALPHANUMERIC_ERR = 'ALPHANUMERIC_ERR';
export const ALPHANUMERIC_HYPHEN_ERR = 'ALPHANUMERIC_HYPHEN_ERR';
export const ALPHANUMERICSPL_ERR = 'ALPHANUMERICSPL_ERR';
export const ALPHANUMERICSPECSPL_ERR = 'ALPHANUMERICSPECSPL_ERR';
export const EMAIL_ERR = 'EMAIL_ERR';
export const THREEREPEATINGCHAR_ERR = 'THREEREPEATINGCHAR_ERR';
export const THREESEQUENCECHAR_ERR = 'THREESEQUENCECHAR_ERR';
export const MINMAXAMOUNT_ERR='MINMAXAMOUNT_ERR';
export const AMOUNTTHREEDECIMAL_ERR='AMOUNTTHREEDECIMAL_ERR';
export const MOBILENUMBER_EIGHTDIGIT_ERR='MOBILENUMBER_EIGHTDIGIT_ERR';
export const MOBILENUMBER_NONZERO_ERR='MOBILENUMBER_NONZERO_ERR';
export const IBAN_DIGIT_ERR='IBAN_DIGIT_ERR';
export const SHOULDALLOWEDLENGTH_ERR = 'SHOULDALLOWEDLENGTH_ERR';
export const MANDATORYSELECT_ERR = 'MANDATORYSELECT_ERR';
export const NOTBEGINWITH_SPACE_ERR = 'NOTBEGINWITH_SPACE_ERR';
export const CHECKBOX_ERR= 'CHECKBOX_ERR';
export const MIN_CHAR_WITHOUT_SPACE='MIN_CHAR_WITHOUT_SPACE';
export const CONCECUTIVE_SPACE_ERR='CONCECUTIVE_SPACE_ERR';
export const ALLOW_SPACE_ERR = 'ALLOW_SPACE';
export const ALPHANUMERICSPL_WITHSPACE_ERR = 'ALPHANUMERICSPL_WITHSPACE_ERR';
export const THREEDECIMAL_ERROR = 'THREEDECIMAL_ERROR';
export const FROMDATE_TODATE_SAME = 'FROMDATE_TODATE_SAME';
export const FROMDATE_GREATERTHAN_TODATE = 'FROMDATE_GREATERTHAN_TODATE';
export const FROMDATE_LESSERTHAN_TODATE = 'FROMDATE_LESSERTHAN_TODATE';
export const TRIP_EXIST = 'TRIP_EXIST';
export const ID_LENGTH_ERR = 'ID_LENGTH_ERR';
export const IS_DATE = 'IS_DATE';
export const ALPHA_ALLOW_SPACE_ERR = 'ALPHA_ALLOW_SPACE_ERR';
export const MANDATORYSELECT_AMOUNT = 'MANDATORYSELECT_AMOUNT';
export const TERMSANDCONDITION_ERROR = 'TERMSANDCONDITION_ERROR';
export const CARDRELOAD_MANDATORYTEXT = 'CARDRELOAD_MANDATORYTEXT';
export const CARDRELOAD_MANDATORYDROPDOWN = 'CARDRELOAD_MANDATORYDROPDOWN';
export const CARDRELOAD_LENGTHVALIDATION = 'CARDRELOAD_LENGTHVALIDATION';
export const ALPHA_WITH_SPACE_ERR = 'ALPHA_WITH_SPACE_ERR';
export const IS_TWO_WORDS = 'IS_TWO_WORDS';
export const IS_MULTIPLE_25 = 'IS_MULTIPLE_25';
export const MINAMOUNT_ERR = 'MINAMOUNT_ERR';
export const INVALID_DATE_ERR = 'INVALID_DATE_ERR';
export const DATE_RANGE_ERR = 'DATE_RANGE_ERR';
export const DATE_VALID_ERR = 'DATE_VALID_ERR';
export const MIN_DATE_EXCEED_ERR = 'MIN_DATE_EXCEED_ERR';
export const CUS_MIN_LENGTH_ERR = 'CUS_MIN_LENGTH_ERR';
export const CUS_MAX_LENGTH_ERR = 'CUS_MAX_LENGTH_ERR';
export const NON_ZERO = 'NON_ZERO';
export const LESS_THEN_ZERO = 'LESS_THEN_ZERO';
export const CUS_PATTERN_VALIDATOR = 'CUS_PATTERN_VALIDATOR';
export const MIN_MAX_DATE_CHECKER = 'MIN_MAX_DATE_CHECKER';
export const MONTH_END_DATE_CHECKER = 'MONTH_END_DATE_CHECKER';










